vault:
  path: ~/vault-fs

presets:
  basic:
    directories:
      - Daily Debrief
      - Daily Plan
      - Journal
      - Meeting Notes
      - Projects/Active
      - Projects/Archived
      - Reports
      - Scratchpad
      - Stakeholders
